name: Conditional versioning

on:
  push:
    branches:
      - main
    tags:
      - "**"

  workflow_run:
    workflows: ["tagging"]
    types:
      - completed

jobs:
  notion-versioning:
      if: >
        github.event_name == 'workflow_run' ||
        (
          github.event_name == 'push' &&
          startsWith(github.ref, 'refs/tags/v')
        )
      name: request API
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          id: git_checkout
          uses: actions/checkout@v3
          with:
            ref: ${{ github.ref }}

        - name: Get current ISO8601 formatted date
          id: get-date
          run: |
            sudo timedatectl set-timezone Asia/Seoul
            echo ::set-output name=date::$(date +"%Y-%m-%dT%H:%M:%SZ")
        
        - name: Get tag
          run: |
            git fetch --prune --unshallow
            git describe --tags `git rev-list --tags --max-count=1` > tag_name
            echo "VERSION=$(cat tag_name)" >> $GITHUB_ENV
            echo "SUBJECT=$(git tag -l --format="%(subject)" `cat tag_name`)" >> $GITHUB_ENV
            echo "TAGGER=$(git tag -l --format="%(tagger)" `cat tag_name` | cut -d "<" -f1)" >> $GITHUB_ENV
        
        - name: Result for API
          run: |
            echo "ref: ${{ github.ref_name }} " >> $GITHUB_STEP_SUMMARY
            echo "time: ${{ steps.get-date.outputs.date}} " >> $GITHUB_STEP_SUMMARY
            echo "version: ${{ env.VERSION }} " >> $GITHUB_STEP_SUMMARY
            echo "subject: ${{ env.SUBJECT }} " >> $GITHUB_STEP_SUMMARY
            echo "tagger: ${{ env.TAGGER }} " >> $GITHUB_STEP_SUMMARY
            