name: Notion Versioning

on:
  push:
    tags:
      - "**"

jobs:
  notion-versioning:
    if: startsWith(github.ref, 'refs/tags/v')
    name: request API
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: git_checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Get current ISO8601 formatted date
        id: get-date
        run: |
          sudo timedatectl set-timezone Asia/Seoul
          echo ::set-output name=date::$(date +"%Y-%m-%dT%H:%M:%SZ")

      - name: Get tag
        id: get-tag
        run: |
          _subject=$(git tag --format="%(subject)")
          _type=${_subject} | sed -r "s/\[.*\]\[(.+)\].*/\1/"
          echo ::set-output name=subject::${_subject,,}
          echo ::set-output name=type::${type,,}
          if [[ _type == "" ]]
          then
            _type="기타"
          fi
          echo ::set-output name=tagger::$(git tag --format="%(tagger)") | cut -d "<" -f1

      - name: Request API with curl
        id: request
        run: |
          curl -X POST 'https://api.notion.com/v1/pages' \
            -H 'Authorization: Bearer ${{ secrets.NOTION_KEY }}' \
            -H "Content-Type: application/json" \
            -H "Notion-Version: 2022-06-28" \
            --data '{
              "parent": {
                "database_id": "b2abb39699af45f69d06b7b8ca3b3453"
              },
              "properties": {
                "개정 버전": {
                  "title": [
                    {
                      "type": "text",
                      "text": {
                        "content": "${{ github.ref_name }}"
                      }
                    }
                  ]
                },
                "개정일": {
                  "date": {
                    "start": "${{ steps.get-date.outputs.date}}",
                    "time_zone": "Asia/Seoul"
                  }
                },
                "설명": {
                  "rich_text": [
                    {
                      "type": "text",
                      "text": {
                        "content": "${{ steps.get-tag.outputs.subject }}"
                      }
                    }
                  ]
                },
                "담당자": {
                  "rich_text": [
                    {
                      "type": "text",
                      "text": {
                        "content": "${{ steps.get-tag.outputs.tagger }}"
                      }
                    }
                  ]
                },
                "타입": {
                  "select": {
                    "name": "${{ steps.get-tag.outputs.type }}"
                  }
                }
              }
            }'
