name: Notion Versioning

on:
  push:
    tags:
      - "**"

jobs:
  notion-versioning:
    if: startsWith(github.ref, 'refs/tags/v')
    name: request API
    runs-on: ubuntu-latest

    steps:
      - name: Get current ISO8601 formatted date
        id: get-date
        run: echo ::set-output name=date::date -Is

      - name: Get tag subject
        id: get-subject
        run: echo "subject=$(git tag -l --format='%(contents:subject)'${GITHUB_REF#refs/*/})" >> $GITHUB_ENV

      - name: Request API with curl
        id: request
        run: |
          curl -X POST 'https://api.notion.com/v1/pages' \
            -H 'Authorization: Bearer ${{ secrets.NOTION_KEY }} \
            -H "Content-Type: application/json" \
            -H "Notion-Version: 2022-06-28" \
            --data '{
              "parent": {
                "database_id": "b2abb39699af45f69d06b7b8ca3b3453"
              },
              "properties": {
                "개정 버전": {
                  "title": [
                    {
                      "type": "text",
                      "text": {
                        "content": "${{ github.ref_name }}"
                      }
                    }
                  ]
                },
                "개정일": {
                  "date": {
                    "start": "${{ steps.get-date.outputs.date}}",
                    "time_zone": "Asia/Seoul"
                  }
                },
                "설명": {
                  "rich_text": [
                    {
                      "type": "text",
                      "text": {
                        "content": "${{ env.subject }}"
                      }
                    }
                  ]
                }
              }
            }'

        # echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"
