name: test

on:
  workflow_run:
    workflows: ["tagging"]
    types:
      - completed

jobs:
  no-if:
    runs-on: ubuntu-latest

    steps:
      - name: Echo
        run: echo ${{ github.ref }}

  if:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - name: Echo
        run: echo ${{ github.ref }}
