name: notion_versioning2

on:
  push:
    branches:
      - main
    tags:
      - "**"

  workflow_run:
    workflows: ["tagging"]
    types:
      - completed

jobs:
  notion-versioning:
      if: >
        github.event_name == 'workflow_run' ||
        (
          github.event_name == 'push' &&
          startsWith(github.ref, 'refs/tags/v')
        )
      name: request API
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          id: git_checkout
          uses: actions/checkout@v3

        - name: Get current ISO8601 formatted date
          id: get-date
          run: |
            sudo timedatectl set-timezone Asia/Seoul
            echo ::set-output name=date::$(date +"%Y-%m-%dT%H:%M:%SZ")

        - name: Get tag on push event
          id: get_by_push
          if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
          run: |
            _subject=$(git tag --format="%(subject)")
            echo ::set-output name=version::${{ github.ref_name }}
            echo ::set-output name=subject::${_subject,,}
            echo ::set-output name=tagger::$(git tag --format="%(tagger)") | cut -d "<" -f1
        
        - name: Get tag on workflow_run event 
          id: get_by_merge
          if: github.event_name == 'workflow_run'
          run: |
            git fetch --prune --unshallow
            git describe --tags `git rev-list --tags --max-count=1` > tag_name
            _subject=$(git tag -l --format="%(subject)" `cat tag_name`)
            echo ::set-output name=version::$(cat tag_name)
            echo ::set-output name=subject::${_subject}
            echo ::set-output name=tagger::$(git tag --format="%(tagger)" `cat tag_name`) | cut -d "<" -f1
        
        - name: Test
          run: |
            echo "ref: ${{ github.ref_name }} " >> $GITHUB_STEP_SUMMARY
            echo "time: ${{ steps.get-date.outputs.date}} " >> $GITHUB_STEP_SUMMARY
            echo "version: ${{ steps.get-tag.outputs.version }} " >> $GITHUB_STEP_SUMMARY
            echo "subject: ${{ steps.get-tag.outputs.subject }} " >> $GITHUB_STEP_SUMMARY
            echo "tagger: ${{ steps.get-tag.outputs.tagger }} " >> $GITHUB_STEP_SUMMARY
            